theme: "hugo-theme-novela"
baseURL: "https://example.com"
languageCode: "en-us"
title: "Avery and Sean Collaboration Hub"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
